# Proposal report


## Executive Summary

Currently, tutors are relying primarily on manual processes and human memory to track student progress. This often leads to a lack of reliable and timely signals as to which areas students are struggling with. Similarly, parents often get inconsistent and unclear pictures of how their children are progressing.
Our solution would be to provide tutors with a fully functional pipeline and dashboard that would provide them with all the necessary tools to track student progress with specific skills and ensure that they can get timely signals to detect potentially problematic areas for students.

## Introduction


The problem that we are tackling in this project is to help teachers track student progress through time. This would allow us to ensure parents and students get timely feedback in a clear and concise manner.
Knowledge tracing is a machine learning method to track and predict a student’s mastery over time based on their performance data.
We have 3 main objectives for this project :
- Create a mastery tracker that uses knowledge tracing to estimate student's mastery probability
- Create an early warning system that flags areas that students are struggling with
- Create a dashboard application visualises the elements above and other students insights (e.g average scores)
The outcome of the project would be a fully functional and reproducible pipeline that updates the dashboard when given new data.


## Data & Exploratory Data Analysis (EDA)


The dataset comes from an AP Statistics course and contains information about the course structure (number of assignments and classes), the knowledge structure (knowledge components and their relationships) and the student response structure (performance data for 25 students). It spans across 3 homework assignments (69 observations total), 27 knowledge components (38 edges between KCs) and 25 students for a total of 1725 item-level student records.
The observational unit in this dataset is the student's grades which can be found in the Student_Observations file in the score column. This provides insights into the students' performance.
The knowledge components are skills that students need to complete skills. These components are inter-dependent, with some KCs being prerequisites for others. This is what we are trying to estimate the mastery of.


### Key insights


- KC coverage imbalance
There is an imbalance in the number of observations for each knowledge component, with some having only 25 observations (i.e 1 per student) while others contain 175 observations (i.e 7 per student). This imbalance needs to be taken into account when modelling, since it means that the values estimated for the KCs with little number of observations are likely to be inaccurate.

- Wide spread within assignments
Within the assignments there is a wide spread of performances with some students scoring consistently above 80% while others are below 50%. The shift in distribution range between homework 1 and 3 should also be considered


- Performance band imbalance
The performance band distributions are also somewhat imbalanced, with there being 2 times more proficient students than emerging. This might lead to some prediction issues in the model building phase, especially when trying to make predictions for emerging students. This can be especially problematic since these are the students that the early warning system should flag


- Knowledge component relationships
Some knowledge components are prerequisites of each other, which means that in order for a student to have mastered a KC, they need to have mastered all of its prerequisites. This is something that needs to be taken into account when modelling.


## Data Science Approach

Estimating student progress by building knowledge profiles for each student. In these profiles, each KC will have its corresponding mastery probability, where the mastery probability is the probability that a student has mastered that KC. 

We will start by estimating the mastery probability using BKT and using this model as a baseline. This model assumes all KC are independent.
We use BKT as baseline since it is very interpretable, and has few parameters

We will then be building more complex models that take into account the relationships between KCs. THen we will compare performance between models and choose the model we will use to build the profile.

We will then display the results from the mastery tracker in a dashboard. This dashboard will display the knowledge profile as well as other insight into the students performance (Average grades…)

We will also be prototyping an early warning system that sends out an alert or flags KCs that students are struggling with (mastery probability below a certain threshold).
Also a recommender system that suggests the next steps a student can take once they've mastered a KC (mastery probability above a certain threshold).




